

import streamlit as st
from streamlit_map import mapcsv
from streamlit_map import mapgeojson
from streamlit_map import mapbbox

import questions
import api_calls


##Page configuration
st.set_page_config(
    page_title="Genes from Space Monitoring Tool",
    page_icon="🌍",
    layout="wide",
    initial_sidebar_state="expanded",
    menu_items={
        'Get Help': 'https://teams.issibern.ch/genesfromspace/',
        'Report a bug': "https://teams.issibern.ch/genesfromspace/",
        'About': "# This is a header. This is an *extremely* cool app!"
    }
)

#session state initialization
#saves the Inputs for Pipeline selection
if "save" not in st.session_state:
    st.session_state.save= {}
    st.session_state.save["poly"]=""
    st.session_state.save["points"]=""
#used to check if the user has changed the selection
if "savecheck" not in st.session_state:
    st.session_state.savecheck= {}
#saves the type of pipeline
if "type" not in st.session_state:
    st.session_state.type= {}
#used to check if the user has clicked on the commit button
if "commit" not in st.session_state:
    st.session_state.commit=False
#saves inputs for pipeline
if "input" not in st.session_state:
    st.session_state.input= {}

types = {
    "LC_bbox": {"LCtype": "Landcover (ESA)", "poly": "no", "points": "Retrieved from GBIF", "area_type": "Bounding box"},
    "TC_bbox": {"LCtype": "Tree cover (GFW)", "poly": "no", "points": "Retrieved from GBIF", "area_type": "Bounding box"},
    "LC_country": {"LCtype": "Landcover (ESA)", "poly": "no", "points": "Retrieved from GBIF", "area_type": "Country"},
    "TC_country": {"LCtype": "Tree cover (GFW)", "poly": "no", "points": "Retrieved from GBIF", "area_type": "Country"},
    "LC_poly": {"LCtype": "Landcover (ESA)", "poly": "yes", "points": "NA", "area_type": "NA"},
    "TC_poly": {"LCtype": "Tree cover (GFW)", "poly": "yes", "points": "NA", "area_type": "NA"},
    "LC_obs": {"LCtype": "Landcover (ESA)", "poly": "no", "points": "User-provided", "area_type": "NA"},
    "TC_obs": {"LCtype": "Tree cover (GFW)", "poly": "no", "points": "User-provided", "area_type": "NA"}
}

urls = {
    "LC_bbox": "http://130.60.24.27/pipeline-form/GenesFromSpace%3ETool%3ELand_cover_v_GBIF_bbox",
    "TC_bbox": "http://130.60.24.27/pipeline-form/GenesFromSpace%3ETool%3EForest_cover_v_GBIF_bbox",
    "LC_country": "http://130.60.24.27/pipeline-form/GenesFromSpace%3ETool%3ELand_cover_v_GBIF_countries",
    "TC_country": "http://130.60.24.27/pipeline-form/GenesFromSpace%3ETool%3EForest_cover_v_GBIF_countries",
    "LC_poly": "http://130.60.24.27/pipeline-form/GenesFromSpace%3ETool%3ELandcover_v_polygon",
    "TC_poly": "http://130.60.24.27/pipeline-form/GenesFromSpace%3ETool%3EForestcover_v_polygon",
    "LC_obs": "http://130.60.24.27/pipeline-form/GenesFromSpace%3ETool%3ELandcover_v_obs_server",
    "TC_obs": "http://130.60.24.27/pipeline-form/GenesFromSpace%3ETool%3EForest_cover_v_obs_server"
}


##Header
st.markdown("# Genes from Space Monitoring Tool")
st.markdown('''
The Genes From Space monitoring tool uses Earth Observations (EO) to track habitat changes over time and infer population trends as indicators of genetic diversity.  
''')
with st.expander("**-> What can the tool be used for?**"):
    st.markdown('''Leveraging public EO data, the tool enables users to estimate two genetic diversity indicators adopted by the Convention on Biological Diversity:
- the **Ne500 indicator**, indicating the fraction of populations with an effective population size (Ne) above 500 units. Populations with Ne below 500 units are at risk of genetic erosion.
- the **Populations Maintained indicator (PM)**, indicating the fraction of populations that are maintained (i.e., that did not extinct) over time.
\nDeveloped within the BON in a box platform, the tool simplifies the process of accessing EO datasets, running analyses, and estimating genetic diversity indicators. Ultimately, this tool offers a scalable and accessible solution for researchers, conservationists, and policymakers to monitor and protect biodiversity at local, regional, and global levels.
\nFor detailed information on methods and assumptions underlying the tool, check out the [Genes from Space](https://teams.issibern.ch/genesfromspace/) website.
''')

with st.expander("**-> How does the tool work?**", expanded=False):
        st.markdown('''The figure below provides an overview of how the tool works. There a two main  main inputs:
                    \n1. **Populations Distribution Map**: This map represents the geographic distribution of the species' populations, typically derived from field observations of the studied species. The observation can be provided by the user, or retrieved from a public repository (GBIF) using the tool. 
                    \n2. **Habitat Suitability Maps**: These maps depict changes in the species' suitable habitat over time. These maps are generated by the tool using Earth observation-derived data and models. 
    \nUsing these inputs, the tool assesses how the size of suitable habitat for each population changes over time. This analysis can identify populations that have completely lost their habitat over a given period (estimating the PM indicator). Additionally, by combining suitable habitat size with an estimate of population density, the tool can estimate the size of each population, which is then used to estimate the Ne500 indicator.
    \nThe interactive form will ask which data to use for representing the populations distribution, habitat change, and set the parameters to estimate the indicators. 
    ''')
        st.image("images/pipeline_description.png")

with st.expander("**-> How to run the tool?**", expanded=False):
        st.markdown('''
The tool runs within [Bon in a Box](https://boninabox.geobon.org/), a platform designed to develop and share tools that support biodiversity monitoring. 
            The tool can be launched through the standard  [BON in a Box interface](http://130.60.24.27/pipeline-form); however, the numerous options and parameters 
            may make this challenging for beginners. To address this, we propose the **interactive form** below, which guides users 
            through the preparation and execution of a run with the tool.
            ''')


st.divider() 


### Interactive form

st.markdown('### Run the tool via the  Interactive Form')
st.markdown('Use the form below to prepare and launch your tool run. As you complete each field, the form will dynamically reveal new options, guiding you step-by-step through the setup process.')



###Pipeline Selection
st.markdown('##### Step 1: Select habitat change dataset')
st.markdown('Choose the satellite-derived dataset that will be used to describe habitat changes for the species of interest. This dataset provides information on how suitable habitats for the species populations have evolved over time.')
with st.expander("**-> Which datasets are available?**", expanded=False):
    st.markdown('''
    The tool currently offers two options for estimating changes in suitable habitat over time:
    1. **[Landcover from the European Space Agency](https://www.esa-landcover-cci.org/)**
    \t* Provides global maps showing annual changes across 30 landcover classes. These classes are standardized and describe the features covering the Earth's surface, such as evergreen forests, deciduous forests, grasslands, agricultural areas, urban areas, and water bodies.
    \t* Ideal for analyzing large spatial scales (entire countries), or when focusing on non-forest species (e.g., species in low-vegetation habitats) or species associated with specific forest types (e.g., needle-leaved, evergreen, or deciduous forests).
    \t* Resolution: 300 meters.
    \t* Timeframe: 1992–2021.
    2. **[Tree Cover from Global Forest Watch](https://www.globalforestwatch.org/)**
    \t* Offers global maps detailing annual tree cover loss.
    \t* Best suited for studying forest species in small geographic regions with homogenous forest types.
    \t* Resolution: 20 meters.
    \t* Timeframe: 2000–2023.
    ''')

LCtype= st.selectbox(
        '**Habitat change Variable:**',
        ('Landcover (ESA)', 'Tree cover (GFW)'),
        index=None,
        placeholder="Select habitat change dataset")


st.divider() 

if LCtype:
    #save LCtype
    st.session_state.save["LCtype"]=LCtype

    st.markdown('##### Step 2: Define the geographic distribution of populations')
    st.markdown('Population polygons represent the geographic distribution of the studied populations. These polygons can be provided as vector files in “geojson” format, with an attribute named “pop” encoding a unique identifier for each population (e.g., “pop_1,” “pop_2,” “pop_3,” etc.). If you already have the polygons in GeoJSON format, you can upload them directly to the tool. If not, the tool includes functionality to generate these polygons from species observations.')

    poly=st.radio(
        "**Do you already have population polygons available?**",
        key="visibility",
        options=["yes", "no"],
        index=None
    )
    
    if poly=="yes":
        st.session_state.save["poly"]="yes"
        st.session_state.save["points"]="NA"
        st.session_state.save["area_type"]= "NA"

    if poly=="no":

        st.markdown('If population polygons are not available, the tool can generate them using species observation coordinates. Below, specify how you will provide these observation coordinates.')
        
        with st.expander("**-> How to provide species coordinates?**", expanded=False):
            st.markdown('''The tool can generate population polygons by processing geographic coordinates of species observations. These coordinates can either be supplied by the user (Figure below, option 1) or retrieved from a public species observation repository [GBIF](https://www.gbif.org/); option 2). 
        ''')
            st.image("images/polygons_option1.png")
            st.image("images/polygons_option2.png")

        #correct the save state if the user changes the selection after commiting.  prevents the commit button from appearing prematurely
        if st.session_state.save["poly"]=="yes":
            del st.session_state.save["area_type"]
        st.session_state.save["poly"]="no"

        points=st.radio(
            "**How will species observation coordinates be provided?**",
            options=["User-provided","Retrieved from GBIF"],
            index=None
        )


        if points=="User-provided":
                st.session_state.save["points"]="User-provided"
                st.session_state.save["area_type"]= "NA"

        if points=="Retrieved from GBIF":
            #correct the save state if the user changes the selection after commiting. prevents the commit button from appearing prematurely
            if st.session_state.save["points"]=="User-provided":
                del st.session_state.save["area_type"]

            st.session_state.save["points"]="Retrieved from GBIF"

            st.markdown('''Species observation coordinates will be provided from GBIF for a given area of interest. The area of interest can be set in two ways:
                        \n- Bounding box: the user draws the area of interest on an interactive map. 
                        \n- Country list: the user selects one or more countries of interest from a list. 
            ''')


            area_type=st.radio(
                "**How will the GBIF region of interest be specified?**",
                options=["Bounding box", "Country"],
                index=None
            )

            if area_type:
                        st.session_state.save["area_type"]=area_type



#Display Commit button if all inputs are selected
if len(st.session_state.save)==4:
    #st.divider() 
    #st.write("You’ve completed the first part of the form, which defines the global parameters for the tool. To proceed to the second part and configure run-specific parameters, click the button below.")
    #if st.button("Set run-specific parameters"):
    st.session_state.commit=True
    st.session_state.savecheck=st.session_state.save.copy()
    st.session_state.input=None

    for key, value in types.items():
        st.session_state.type[key] = st.session_state.save == value


    #Display Input fields if the user only if the selected inputs are commited  
    if st.session_state.savecheck==st.session_state.save:
        for key, value in st.session_state.type.items():
            if value:
    #get script from questions.py for the selected pipeline
                script=getattr(questions, key)
                inputs=script()
                if inputs:
                    st.write(st.session_state.input)
    #Run Bon in a Box with selected inputs via API call script
                    if st.button("Run Script"):
                        for key, value in st.session_state.type.items():
                            func = None
                            if value:
                                func = getattr(api_calls, key)

                            if func:
                                link="http://130.60.24.27/pipeline-form/"+func(st.session_state.input).text[:-33] + '/' + func(st.session_state.input).text[-32:]
                                st.write(link)
                                #webbrowser.open(link)
                            
